"""initial migration

Revision ID: 79146f7c453e
Revises: 
Create Date: 2025-01-26 17:14:10.132775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79146f7c453e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('_password_hash', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
